---
- name: package installer
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: installing httpd
    yum:
      name: httpd
      state: installed

  - name: starting httpd service 
    service:
      name: httpd
      state: started
  
  - copy:
      src: /home/ansadmin/playbooks/index.html
      dest: /var/www/html

