---
- name: installing on rhel and ubuntu
  hosts: all
  gather_facts: yes
  become: true

  tasks:
  - name: install httpd on rhel
    yum:
      name: httpd
      state: installed
    when: ansible_distribution == "RedHat"

  - name: install httpd on ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"
 
  - name: starting httpd on rhel
    service:
      name: httpd
      state: started 
    when: ansible_distribution == "RedHat"
    
  - name: starting httpd on ubuntu
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"
